<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-21T09:48:02 IST" name="Suite" finished-at="2022-12-21T09:48:51 IST" duration-ms="48326">
    <groups>
    </groups>
    <test started-at="2022-12-21T09:48:02 IST" name="TestQA" finished-at="2022-12-21T09:48:51 IST" duration-ms="48326">
      <class name="scripts.InvalidLogin">
        <test-method is-config="true" signature="createReport()[pri:0, instance:scripts.InvalidLogin@663c9e7a]" started-at="2022-12-21T09:48:02 IST" name="createReport" finished-at="2022-12-21T09:48:02 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReport -->
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.reflect.Method)[pri:0, instance:scripts.InvalidLogin@663c9e7a]" started-at="2022-12-21T09:48:02 IST" name="openApp" finished-at="2022-12-21T09:48:14 IST" duration-ms="11261" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa.properties]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void scripts.InvalidLogin.testInvalidLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testInvalidLogin()[pri:0, instance:scripts.InvalidLogin@663c9e7a]" started-at="2022-12-21T09:48:14 IST" name="testInvalidLogin" finished-at="2022-12-21T09:48:35 IST" duration-ms="21289" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home page is not displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home page is not displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at scripts.InvalidLogin.testInvalidLogin(InvalidLogin.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:scripts.InvalidLogin@663c9e7a]" started-at="2022-12-21T09:48:35 IST" name="closeApp" finished-at="2022-12-21T09:48:35 IST" duration-ms="359" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testInvalidLogin status=FAILURE method=InvalidLogin.testInvalidLogin()[pri:0, instance:scripts.InvalidLogin@663c9e7a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="publishReport()[pri:0, instance:scripts.InvalidLogin@663c9e7a]" started-at="2022-12-21T09:48:51 IST" name="publishReport" finished-at="2022-12-21T09:48:51 IST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- publishReport -->
      </class> <!-- scripts.InvalidLogin -->
      <class name="scripts.ValidLogin">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.reflect.Method)[pri:0, instance:scripts.ValidLogin@4b013c76]" started-at="2022-12-21T09:48:35 IST" name="openApp" finished-at="2022-12-21T09:48:46 IST" duration-ms="10775" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa.properties]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void scripts.ValidLogin.testValidLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testValidLogin()[pri:1, instance:scripts.ValidLogin@4b013c76]" started-at="2022-12-21T09:48:46 IST" name="testValidLogin" finished-at="2022-12-21T09:48:51 IST" duration-ms="4423" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:scripts.ValidLogin@4b013c76]" started-at="2022-12-21T09:48:51 IST" name="closeApp" finished-at="2022-12-21T09:48:51 IST" duration-ms="175" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testValidLogin status=SUCCESS method=ValidLogin.testValidLogin()[pri:1, instance:scripts.ValidLogin@4b013c76] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- scripts.ValidLogin -->
    </test> <!-- TestQA -->
  </suite> <!-- Suite -->
</testng-results>
